import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Script from "next/script";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <Script id="Caspeco">
                    {`
                        (function(w, d, s, id, cso) {
                            w['CaspecoSDKObject'] = cso;
                            var js, cjs = d.getElementsByTagName(s)[0];
                            if (d.getElementById(id)) return;
                            js = d.createElement(s); js.id = id;
                            js.src = 'https://bookingsdk.caspeco.net/sv_SE/sdk.js';
                            cjs.parentNode.insertBefore(js, cjs);
                        }(window, document, 'script', 'caspeco-sdk', 'ca'));
                    `}
                </Script>
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <ul>
                    <li>
                        <Link href={"/"}>Home</Link>
                    </li>
                    <li>
                        <Link href={"/about"}>About</Link>
                    </li>
                </ul>
                {children}
            </body>
        </html>
    );
}
